### ISSUE TITLE
Wrong Export format

### ISSUE THREAD

**Issue by Alaggaerion** [UnopenedClosure/EmeraldKaizo#2]
exportall() command is not exporting properly Male Nidoran (probably female too), result should be Nidoran-M and Nidoran-F instead of Nidoran♂ and Nidoran♀

**Comment by UnopenedClosure** [comment]
This was fixed in a PR a couple days ago. Please pull the latest version and try again

**Comment by Alaggaerion** [comment]
oh sorry didn't noticed it indeed, however I just tested it and I get "Nidoran-m" from the export (and the damage calc is willing an upper case M).
